version: '3'
 
services:
    reverseproxy:
        build: .
        tty: true
        ports:
            - 8080:8080
            - 8081:8081
        restart: always
 
    nginx:
        tty: true
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    apache:
        tty: true
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always